debug: false
host: "127.0.0.1"
port: 2000
timeout: 10
res: "1280x720"
width: ???
height: ???

# Simulation mode
sync: true
fixed_step: 0.03
filter: "vehicle.audi.etron"
generation: "1"
loop: false
seed: null

# Agent
agent: "Behavior"         # options: Behavior, Basic, Constant
behavior: "normal"        # only applies if agent == "Behavior"
spawn_point: [-250,250]
#Map
map: "Town06"